routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('notes', 'NoteController');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    //

    protected $fillable = [
        'title', 'points', 'posted',
    ];

}

?>

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;
use App\Note;
use Illuminate\Http\Request;
use DateTime;
class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $notes = Note::all();
        return view('notes.index', compact('notes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('notes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'points' => 'required'
        ]);
        $now = new Datetime;
        $new = new Note([
            'title' => $request->get('title'),
            'points' => $request->get('points'),
            'posted' => $now
        ]);
        $new->save();
        return redirect('/notes')->with('success', 'New notes successfully saved!.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $note = Note::find($id);
        return view('notes.edit', compact('note'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'points'=>'required'
        ]);
        $note = Note::find($id);
        $note->title = $request->get('title');
        $note->points = $request->get('points');
        $now = new DateTime();
        $note->posted = $now;
        $note->save();
        return redirect('/notes')->with('success', 'Notes has been edited successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $note = Note::find($id);
        $note->delete();
        return redirect('/notes')->with('success', 'Notes has been removed');
    }
}

resources/views/notes/create.blade.php
@extends('template')

    @section('main')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h2 class="text-center font-weight-bold">Add Notes</h2>
        <div>

            @if ($errors->any())

        <div class="alert alert-danger">

            <ul>
                @foreach ($errors->all() as $error)
                     <li>{{ $error }}</li>
                @endforeach
            </ul>

        </div>
        <br />

        @endif

        <form method="post" action="{{ route('notes.store') }}">
            @csrf

            <div class="form-group">
                <label for="Title">Title</label>
                <input type="text" class="form-control" name="title"/>
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea rows="2" class="form-control" name="points"></textarea>
            </div>
            <div class="float-right">
                <a role="button" class="btn btn-dark" href="{{route('notes.index')}}">Back</a>
                <button type="submit" class="pull-right btn btn-success">Create New Note</button>

            </div>
        </form>
    </div>
    </div>
    </div>
    @endsection

resources/views/notes/edit.blade.php
@extends('template')
    @section('main')
    <div class="row" style="margin-top:20px;">
        <div class="col-md-2">
        </div>

        <div class="col-md-8">
            <form action="{{ route('notes.update', $note->id) }}" method="post">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group">
                    <label for="Title">Title</label>
                    <input type="text" class="form-control" name="title" value="{{$note->title}}"/>
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea type="text" class="form-control" name="points" value="{{$note->points}}"></textarea>
                </div>

                <div class="float-right">
                <a href="{{route('notes.index')}}" class="btn btn-light">Back</a>
                    <button type="submit" class="btn btn-success">Update Note</button>
                </div>

            </form>
        </div>

        <div class="col-md-2">

        </div>
    </div>

    @endsection

resources/views/notes/index.blade.php
@extends('template')

    @section('main')

    <div class="col-sm-12">

        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
    </div>
            <div class="text-center" style="margin-top: 10px;">
                    <a href="{{ route('notes.create') }}" class="btn btn-primary" >Add New Note</a>
        </div>

        <div class='row' style="margin-top: 50px; justify-content: center;">
            <div class="col-md-1">

            </div>


            <div class="col-md-10">
                <div class="table-responsive">
                    <table class="table table-bordered" style="width: 100% !important;">
                        <thead>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Posted On</th>
                            <th>Timestamps</th>
                            <th>Actions</th>
                            <th></th>
                        </thead>

                        <tbody>
                        @foreach($notes as $note)
                            <tr>
                                <td style="vertical-align: middle;">{{$note->id}}</td>
                                <td style="vertical-align: middle;">{{$note->title}}</td>
                                <td style="margin-left:5px; vertical-align: middle;">{{$note->points}}</td>
                                <td style="margin-left:5px; vertical-align: middle;">{{$note->posted}}</td>
                                <td style="color:blue; vertical-align: middle;">{{$note->created_at}}</td>
                                <div class="btn-group">
                                <td class="text-center"><a href="{{route('notes.edit', $note->id)}}"><button type="button" class="btn btn-info btn-block">Edit</button></a></td>
                                <td>
                                        <form method="post" action="{{route('notes.destroy', $note->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="delete btn btn-danger btn-block">Delete</button>
                                    </form>
                                </td>
                            </div>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-md-1">
            </div>
        </div>
    @endsection

resources/views/template.blade.php
<html>
    <header>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Notes App</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
            <div class="text-center" style="margin-top:10px; text-color=#ffffff">

                <h2>Laravel Notes</h2>
            </div>
        </header>
        <body>
            <div class='container'>
                @yield('main')
            </div>
            <script src="{{ asset('js/app.js') }}" type="text/js"></script>
        </body>
</html>